# This is a basic workflow to help you get started with Actions

name: Pull Requests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  
  build:
  
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
   
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set Version
        run: echo "PACKAGE_VERSION=1.0.$((GITHUB_RUN_NUMBER))" >> $GITHUB_ENV

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
  
      - name: Login to Octopus Deploy 
        uses: OctopusDeploy/login@v1.0.1
        with: 
          server: https://robpearson.octopus.app
          api_key: ${{secrets.OCTOPUS_API_KEY}}
  
      - name: Create Octopus Release
        uses: OctopusDeploy/create-release-action@v3
        with: 
          project: 'B2B Payment Processor'
          channel: 'Pull Requests'
          release_number: ${{ env.PACKAGE_VERSION }}
          release_notes: 'GitHub Commits URL: ${{ github.event.pull_request.commits_url }}'
          git_ref: ${{ (github.ref_type == 'tag' && github.event.repository.default_branch ) || (github.head_ref || github.ref) }}

